services:
  database:
    container_name: creative-score-db
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus_password_change_me'
      POSTGRES_DB: 'directus'
    networks:
      - default

  cache:
    container_name: creative-score-redis
    image: redis:alpine
    restart: always
    networks:
      - default

  directus:
    container_name: creative-score-directus
    image: directus/directus:latest
    restart: always
    ports:
      - 8056:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - database
      - cache
    environment:
      KEY: 'creative-score-key-replace-me'
      SECRET: 'creative-score-secret-replace-me'
      
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus_password_change_me'

      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      REDIS_HOST: 'cache'
      REDIS_PORT: 6379

      ADMIN_EMAIL: 'admin@xerex.tech'
      ADMIN_PASSWORD: 'admin'

      PUBLIC_URL: 'https://score.xerex.tech'
      
      # CORS to allow app to connect
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'https://create.xerex.tech'
      CORS_METHODS: 'GET,POST,PATCH,DELETE'
      
      # Reverse Proxy
      VIRTUAL_HOST: score.xerex.tech
      VIRTUAL_PORT: 8055
      LETSENCRYPT_HOST: score.xerex.tech
      LETSENCRYPT_EMAIL: admin@xerex.tech
    networks:
      - docker-directorios_proxy-net
      - default

  creative-score:
    container_name: creative-score-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DIRECTUS_URL: https://score.xerex.tech
    restart: always
    depends_on:
      - directus
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=create.xerex.tech
      - LETSENCRYPT_HOST=create.xerex.tech
      - LETSENCRYPT_EMAIL=admin@xerex.tech
      # Point to the public URL of the new Directus instance
      - NEXT_PUBLIC_DIRECTUS_URL=https://score.xerex.tech
    expose:
      - 3000
    networks:
      - docker-directorios_proxy-net
      - default

networks:
  docker-directorios_proxy-net:
    external: true
  default:
    driver: bridge

volumes:
  postgres_data:
